import type {
  ChangeLogEntry,
  CheckIn,
  Compound,
  Meal,
  MealTemplate,
  QuoteEntry,
  ScheduleEvent,
  SupplementProtocol,
  TrackerDay,
  TrackerTask,
  WeeklySnapshot,
  WorkoutDay,
} from "./types";

export const scheduleDayOrder = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const;

export const quoteBank: QuoteEntry[] = [
  { text: "Keep showing up. The physique gets built by repeatable days, not dramatic ones.", tone: "steady" },
  { text: "A calm, clean day beats a chaotic hero day every single time.", tone: "calm" },
  { text: "Your edge is consistency with taste, not panic with effort.", tone: "confident" },
  { text: "Stack clean days until the look has no choice but to show up.", tone: "focused" },
  { text: "Pretty, dangerous, and disciplined. That is the assignment.", tone: "chaos" },
];

export const initialCompounds: Compound[] = [
  {
    id: "c1",
    name: "Testosterone Cypionate",
    category: "Base",
    enabled: false,
    dose: 500,
    unit: "mg/week",
    fullness: 2,
    dryness: -1,
    performance: 2,
    recovery: 2,
    stress: 1,
    digestion: 0,
    note: "Stable base androgen.",
    halfLifeDays: 8,
    anabolicRating: 100,
    androgenicRating: 100,
    schedule: [
      { id: "c1d1", day: "Mon", amount: 250 },
      { id: "c1d2", day: "Thu", amount: 250 },
    ],
  },
  {
    id: "c2",
    name: "Drostanolone Enanthate",
    category: "Performance",
    enabled: false,
    dose: 400,
    unit: "mg/week",
    fullness: 0,
    dryness: 5,
    performance: 1,
    recovery: 0,
    stress: 1,
    digestion: 0,
    note: "Dryness and cosmetic support.",
    halfLifeDays: 7.5,
    anabolicRating: 62,
    androgenicRating: 25,
    schedule: [
      { id: "c2d1", day: "Mon", amount: 200 },
      { id: "c2d2", day: "Thu", amount: 200 },
    ],
  },
  {
    id: "c3",
    name: "Trenbolone Enanthate",
    category: "Performance",
    enabled: false,
    dose: 200,
    unit: "mg/week",
    fullness: -1,
    dryness: 4,
    performance: 3,
    recovery: 1,
    stress: 4,
    digestion: -2,
    note: "High-output compound with recovery drag risk.",
    halfLifeDays: 10.5,
    anabolicRating: 500,
    androgenicRating: 500,
    schedule: [
      { id: "c3d1", day: "Tue", amount: 100 },
      { id: "c3d2", day: "Fri", amount: 100 },
    ],
  },
];

export const initialSupplements: SupplementProtocol[] = [
  {
    id: "sp1",
    supplementId: "creatine-monohydrate",
    enabled: true,
    dose: "5 g",
    pattern: "daily",
  },
  {
    id: "sp2",
    supplementId: "caffeine",
    enabled: true,
    dose: "200 mg",
    pattern: "training",
  },
  {
    id: "sp3",
    supplementId: "whey",
    enabled: true,
    dose: "1 scoop",
    pattern: "as-needed",
  },
  {
    id: "sp4",
    supplementId: "electrolyte-mix",
    enabled: true,
    dose: "1 serving",
    pattern: "training",
  },
  {
    id: "sp5",
    supplementId: "fish-oil",
    enabled: false,
    dose: "2 g EPA/DHA",
    pattern: "daily",
  },
];

export const initialMeals: Meal[] = [
  {
    id: "m1",
    name: "Breakfast",
    protein: 0,
    carbs: 0,
    fats: 0,
    timing: "08:00",
    type: "standard",
    timingUse: "flexible",
    note: "Empty meal slot. Log real foods when you actually eat.",
  },
  {
    id: "m2",
    name: "Lunch",
    protein: 0,
    carbs: 0,
    fats: 0,
    timing: "13:00",
    type: "standard",
    timingUse: "flexible",
    note: "Empty meal slot. Log real foods when you actually eat.",
  },
  {
    id: "m3",
    name: "Dinner",
    protein: 0,
    carbs: 0,
    fats: 0,
    timing: "19:00",
    type: "standard",
    timingUse: "flexible",
    note: "Empty meal slot. Log real foods when you actually eat.",
  },
  {
    id: "m4",
    name: "Snack",
    protein: 0,
    carbs: 0,
    fats: 0,
    timing: "21:30",
    type: "standard",
    timingUse: "flexible",
    note: "Empty meal slot. Log real foods when you actually eat.",
  },
];

export const initialMealTemplates: MealTemplate[] = [
  {
    id: "mt1",
    name: "Rice chicken bowl",
    protein: 45,
    carbs: 45,
    fats: 10,
    timing: "12:00",
    type: "standard",
    libraryFoodIds: ["white-rice", "chicken-breast"],
    fiberG: 4,
    sodiumMg: 450,
    potassiumMg: 540,
    fluidMl: 250,
    satietyLevel: "moderate",
    digestionLoad: "moderate",
    micronutrientDensity: "moderate",
    timingUse: "flexible",
    note: "Simple repeatable meal block for any standard slot.",
  },
  {
    id: "mt2",
    name: "Pre-workout bowl",
    protein: 35,
    carbs: 55,
    fats: 6,
    timing: "16:30",
    type: "standard",
    libraryFoodIds: ["cream-of-rice", "whey-isolate", "banana"],
    fiberG: 2,
    sodiumMg: 550,
    potassiumMg: 480,
    fluidMl: 450,
    satietyLevel: "light",
    digestionLoad: "light",
    micronutrientDensity: "moderate",
    timingUse: "flexible",
    note: "Fast, low-friction meal block when training support needs to be clean.",
  },
  {
    id: "mt3",
    name: "Training drink",
    protein: 0,
    carbs: 35,
    fats: 0,
    timing: "17:30",
    type: "intra",
    libraryFoodIds: ["electrolyte-drink"],
    fiberG: 0,
    sodiumMg: 700,
    potassiumMg: 120,
    fluidMl: 750,
    satietyLevel: "light",
    digestionLoad: "light",
    micronutrientDensity: "light",
    timingUse: "intra",
    note: "Optional carbs and electrolytes inside the session, not a full meal.",
  },
  {
    id: "mt4",
    name: "Recovery meal",
    protein: 45,
    carbs: 60,
    fats: 6,
    timing: "19:15",
    type: "post",
    libraryFoodIds: ["white-rice", "chicken-breast", "banana"],
    fiberG: 2,
    sodiumMg: 650,
    potassiumMg: 700,
    fluidMl: 350,
    satietyLevel: "moderate",
    digestionLoad: "light",
    micronutrientDensity: "moderate",
    timingUse: "post",
    note: "Recovery-biased block when the goal is to finish training and move on cleanly.",
  },
  {
    id: "mt5",
    name: "Rest day protein meal",
    protein: 45,
    carbs: 20,
    fats: 15,
    timing: "13:00",
    type: "off",
    libraryFoodIds: ["potato", "chicken-breast", "leafy-greens"],
    fiberG: 7,
    sodiumMg: 450,
    potassiumMg: 1100,
    fluidMl: 200,
    satietyLevel: "high",
    digestionLoad: "moderate",
    micronutrientDensity: "high",
    timingUse: "off",
    note: "Lower-output meal with more satiety and produce support.",
  },
];

export const initialSplit: WorkoutDay[] = [
  {
    id: "d1",
    day: "Day 1",
    focus: "Upper",
    intensity: 7,
    volume: 7,
    systemicLoad: 6,
    exercises: [
      { exerciseId: "incline-bench-press", sets: 5, repRange: "6-8", rir: 2, note: "Primary chest press" },
      { exerciseId: "seated-cable-row", sets: 4, repRange: "8-12", rir: 1, note: "Stable mid-back volume" },
      { exerciseId: "cable-fly", sets: 4, repRange: "10-15", rir: 1, note: "Chest bias" },
      { exerciseId: "straight-arm-pulldown", sets: 3, repRange: "12-15", rir: 1, note: "Lat isolation" },
      { exerciseId: "cable-lateral-raise", sets: 5, repRange: "12-20", rir: 1, note: "Lateral delt bias" },
      { exerciseId: "cable-pressdown", sets: 4, repRange: "10-15", rir: 1, note: "Triceps" },
    ],
    pickerSearch: "",
    pickerCategory: "All",
    pickerMuscle: "All",
    pickerFatigue: "All",
  },
  {
    id: "d2",
    day: "Day 2",
    focus: "Lower",
    intensity: 7,
    volume: 7,
    systemicLoad: 7,
    exercises: [
      { exerciseId: "front-squat", sets: 4, repRange: "6-8", rir: 2, note: "Primary quad pattern" },
      { exerciseId: "romanian-deadlift", sets: 4, repRange: "6-8", rir: 2, note: "Hamstring hinge" },
      { exerciseId: "leg-extension", sets: 4, repRange: "12-15", rir: 1, note: "Quad isolation" },
      { exerciseId: "seated-leg-curl", sets: 4, repRange: "10-15", rir: 1, note: "Hamstring isolation" },
      { exerciseId: "seated-calf-raise", sets: 5, repRange: "10-15", rir: 1, note: "Calves" },
    ],
    pickerSearch: "",
    pickerCategory: "All",
    pickerMuscle: "All",
    pickerFatigue: "All",
  },
  {
    id: "d3",
    day: "Day 3",
    focus: "Rest",
    intensity: 2,
    volume: 1,
    systemicLoad: 1,
    exercises: [],
    pickerSearch: "",
    pickerCategory: "All",
    pickerMuscle: "All",
    pickerFatigue: "All",
  },
];

export const initialCheckIns: CheckIn[] = [];

export const initialTrackerTasks: TrackerTask[] = [];

export const initialSchedule: ScheduleEvent[] = [];

export const initialChangeLog: ChangeLogEntry[] = [];

export const initialWeeklySnapshots: WeeklySnapshot[] = [];

export const initialTrackerDays: TrackerDay[] = [];
