import type { Compound, HormoneKey } from "@/lib/types";

export const defaultCompounds: Compound[] = [
  {
    name: "Testosterone",
    category: "Base",
    enabled: true,
    dose: 200,
    doseRef: 200,
    minDose: 0,
    maxDose: 1000,
    unit: "mg/week",
    mode: "maintain",
    hormoneEffects: { androgen: 6, estrogen: 4, cortisol: -1, insulinSensitivity: 0, water: 3, thyroid: 0 },
    effects: { fullness: 5, dryness: -1, leanness: 0, performance: 5, sleep: 0, digestion: 0 },
    notes: "Higher modeled doses raise androgen tone and usually estrogen conversion / water pressure.",
  },
  {
    name: "Trenbolone",
    category: "Base",
    enabled: true,
    dose: 300,
    doseRef: 300,
    minDose: 0,
    maxDose: 700,
    unit: "mg/week",
    mode: "maintain",
    hormoneEffects: { androgen: 8, estrogen: -1, cortisol: 2, insulinSensitivity: 1, water: -1, thyroid: 0 },
    effects: { fullness: 2, dryness: 4, leanness: 5, performance: 7, sleep: -4, digestion: 0 },
    notes: "Strong androgen signal with possible recovery and sleep tradeoffs in the model.",
  },
  {
    name: "Masteron",
    category: "Base",
    enabled: true,
    dose: 300,
    doseRef: 300,
    minDose: 0,
    maxDose: 700,
    unit: "mg/week",
    mode: "maintain",
    hormoneEffects: { androgen: 5, estrogen: -2, cortisol: 0, insulinSensitivity: 0, water: -2, thyroid: 0 },
    effects: { fullness: 1, dryness: 5, leanness: 2, performance: 3, sleep: 0, digestion: 0 },
    notes: "Modeled as a harder, drier look compound with mild estrogen pressure reduction.",
  },
  {
    name: "Equipoise",
    category: "Base",
    enabled: false,
    dose: 400,
    doseRef: 400,
    minDose: 0,
    maxDose: 1000,
    unit: "mg/week",
    mode: "maintain",
    hormoneEffects: { androgen: 3, estrogen: 1, cortisol: 0, insulinSensitivity: 0, water: 1, thyroid: 0 },
    effects: { fullness: 2, dryness: 1, leanness: 1, performance: 3, sleep: 0, digestion: 0 },
    notes: "Slow-burn compound in the model with mild fullness and androgen support.",
  },
  {
    name: "Growth Hormone",
    category: "Performance",
    enabled: true,
    dose: 6,
    doseRef: 6,
    minDose: 0,
    maxDose: 12,
    unit: "IU",
    mode: "signal",
    hormoneEffects: { androgen: 0, estrogen: 0, cortisol: 0, insulinSensitivity: -1, water: 2, thyroid: 1 },
    effects: { fullness: 8, dryness: 4, leanness: 5, performance: 7, sleep: 2, digestion: -1 },
    notes: "Modeled here as a training-window signal.",
  },
  {
    name: "Humalog",
    category: "Performance",
    enabled: true,
    dose: 10,
    doseRef: 10,
    minDose: 0,
    maxDose: 25,
    unit: "IU",
    mode: "signal",
    hormoneEffects: { androgen: 0, estrogen: 0, cortisol: -1, insulinSensitivity: -3, water: 1, thyroid: 0 },
    effects: { fullness: 9, dryness: -1, leanness: 1, performance: 8, sleep: -1, digestion: -1 },
    notes: "Strong fullness and glycogen signal in the app logic.",
  },
  {
    name: "Retatrutide",
    category: "Performance",
    enabled: true,
    dose: 2,
    doseRef: 2,
    minDose: 0,
    maxDose: 8,
    unit: "mg/week",
    mode: "signal",
    hormoneEffects: { androgen: 0, estrogen: 0, cortisol: 0, insulinSensitivity: 2, water: -1, thyroid: 1 },
    effects: { fullness: -2, dryness: 1, leanness: 7, performance: -2, sleep: -1, digestion: -6 },
    notes: "Can help appetite control but may hurt training digestion.",
  },
  {
    name: "Anavar",
    category: "Orals",
    enabled: false,
    dose: 40,
    doseRef: 40,
    minDose: 0,
    maxDose: 100,
    unit: "mg/day",
    mode: "signal",
    hormoneEffects: { androgen: 3, estrogen: -1, cortisol: 0, insulinSensitivity: 0, water: -1, thyroid: 0 },
    effects: { fullness: 1, dryness: 3, leanness: 2, performance: 3, sleep: 0, digestion: 0 },
    notes: "Modeled as a mild hardening / performance oral with low water pressure.",
  },
  {
    name: "Winstrol",
    category: "Orals",
    enabled: false,
    dose: 30,
    doseRef: 30,
    minDose: 0,
    maxDose: 80,
    unit: "mg/day",
    mode: "signal",
    hormoneEffects: { androgen: 3, estrogen: -2, cortisol: 0, insulinSensitivity: 0, water: -2, thyroid: 0 },
    effects: { fullness: -1, dryness: 5, leanness: 2, performance: 2, sleep: 0, digestion: 0 },
    notes: "Modeled as a drier, harsher look compound that can trade fullness for crispness.",
  },
  {
    name: "Proviron",
    category: "Ancillary",
    enabled: false,
    dose: 50,
    doseRef: 50,
    minDose: 0,
    maxDose: 100,
    unit: "mg/day",
    mode: "maintain",
    hormoneEffects: { androgen: 2, estrogen: -1, cortisol: 0, insulinSensitivity: 0, water: -1, thyroid: 0 },
    effects: { fullness: 0, dryness: 2, leanness: 1, performance: 1, sleep: 0, digestion: 0 },
    notes: "Modeled as a mild androgen / dryness support layer.",
  },
  {
    name: "Aromatase Inhibitor",
    category: "Ancillary",
    enabled: false,
    dose: 1,
    doseRef: 1,
    minDose: 0,
    maxDose: 3,
    unit: "mg/week",
    mode: "signal",
    hormoneEffects: { androgen: 0, estrogen: -4, cortisol: 0, insulinSensitivity: 0, water: -2, thyroid: 0 },
    effects: { fullness: -1, dryness: 4, leanness: 0, performance: -1, sleep: 0, digestion: 0 },
    notes: "Modeled as lowering estrogen and water pressure, with possible fullness tradeoff if pushed too hard.",
  },
  {
    name: "Cabergoline",
    category: "Ancillary",
    enabled: false,
    dose: 0.5,
    doseRef: 0.5,
    minDose: 0,
    maxDose: 2,
    unit: "mg/week",
    mode: "signal",
    hormoneEffects: { androgen: 0, estrogen: 0, cortisol: 0, insulinSensitivity: 0, water: -1, thyroid: 0 },
    effects: { fullness: 0, dryness: 1, leanness: 0, performance: 0, sleep: 0, digestion: -1 },
    notes: "Modeled as a small water-pressure reduction with minimal direct physique impact.",
  },
  {
    name: "Tadalafil",
    category: "Performance",
    enabled: true,
    dose: 5,
    doseRef: 5,
    minDose: 0,
    maxDose: 20,
    unit: "mg",
    mode: "maintain",
    hormoneEffects: { androgen: 0, estrogen: 0, cortisol: 0, insulinSensitivity: 0, water: 0, thyroid: 0 },
    effects: { fullness: 4, dryness: 1, leanness: 0, performance: 3, sleep: 0, digestion: 0 },
    notes: "Baseline vascular support.",
  },
  {
    name: "Caffeine / Pre",
    category: "Performance",
    enabled: true,
    dose: 1,
    doseRef: 1,
    minDose: 0,
    maxDose: 3,
    unit: "serving",
    mode: "signal",
    hormoneEffects: { androgen: 0, estrogen: 0, cortisol: 3, insulinSensitivity: 0, water: 0, thyroid: 0 },
    effects: { fullness: 0, dryness: 1, leanness: 1, performance: 6, sleep: -5, digestion: 0 },
    notes: "Good for output, bad if pushed too late.",
  },
];

export const hormoneScales = [
  "insulin",
  "cortisol",
  "gh_signal",
  "androgen_tone",
  "aldosterone_water",
  "thyroid_drive",
  "estrogen_load",
] as const;

export const hormoneLabels: Record<HormoneKey, string> = {
  insulin: "Insulin Drive",
  cortisol: "Cortisol / Stress",
  gh_signal: "GH Signal",
  androgen_tone: "Androgen Tone",
  aldosterone_water: "Water / Sodium Hold",
  thyroid_drive: "Metabolic Drive",
  estrogen_load: "Estrogen Load",
};

export const baseSchedule = [
  { key: "wake", label: "Wake / Check-In", time: "08:00" },
  { key: "meal1", label: "Meal 1", time: "09:00" },
  { key: "meal2", label: "Meal 2", time: "12:00" },
  { key: "preMeal", label: "Pre-Training Meal", time: "15:30" },
  { key: "gh", label: "GH / Pre Stack", time: "16:40" },
  { key: "insulin", label: "Pre-Training Signal Window", time: "17:15" },
  { key: "train", label: "Train / Intra Starts", time: "17:30" },
  { key: "post", label: "Post Workout Meal", time: "19:15" },
  { key: "final", label: "Final Meal", time: "21:30" },
  { key: "bed", label: "Bed Routine", time: "23:15" },
];
